version: '1'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '80:80'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network
    container_name: node-app-dev
    command: yarn dev -L

networks:
  node-network:
    driver: bridge
