version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment: 
      - PORT=80
    ports:
      - '80:80'
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network
    container_name: node-app
    command: npm start

networks:
  node-network:
    driver: bridge
