jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
orbs:
  heroku: circleci/heroku@0.0.10
  jest: blimmer/jest@0.2.1

version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - jest/test
      - deploy