jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Run tests
          command: run test
      - heroku/deploy-via-git
orbs:
  heroku: circleci/heroku@0.0.10
  jest: blimmer/jest@0.2.1

version: 2.1
workflows:
  test:
    jobs:
      - jest/test:
          context:
            - npm
  heroku_deploy:
    jobs:
      - deploy
# version: 2.1
# orbs:
#   heroku: circleci/heroku@0.0.10
# workflows:
#   heroku_deploy:
#     jobs:
#       - heroku/deploy-via-git